development:
  adapter: postgresql
  encoding: utf8
  database: trim_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: trim_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: trim_production
  pool: 5
  username:
  password:

cucumber:
  <<: *TEST
